config/routes.rb
Rails.application.routes.draw do
  resources :excuses

  get 'welcome/index'

  root 'welcome#index'

end

app/models/excuse.rb
class Excuse < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/excuses_controller.rb
class ExcusesController < ApplicationController
  before_action :set_excuse, only: [:show, :edit, :update, :destroy]

  # GET /excuses
  # GET /excuses.json
  def index
    @excuses = Excuse.all
  end

  # GET /excuses/1
  # GET /excuses/1.json
  def show
  end

  # GET /excuses/new
  def new
    @excuse = Excuse.new
  end

  # GET /excuses/1/edit
  def edit
  end

  # POST /excuses
  # POST /excuses.json
  def create
    @excuse = Excuse.new(excuse_params)

    respond_to do |format|
      if @excuse.save
        format.html { redirect_to @excuse, notice: 'Excuse was successfully created.' }
        format.json { render :show, status: :created, location: @excuse }
      else
        format.html { render :new }
        format.json { render json: @excuse.errors, status: :unprocessable_entity }
      end
    end
  end

  #
  # PATCH/PUT /excuses/1
  # PATCH/PUT /excuses/1.json
  def update
    respond_to do |format|
      if @excuse.update(excuse_params)
        format.html { redirect_to @excuse, notice: 'Excuse was successfully updated.' }
        format.json { render :show, status: :ok, location: @excuse }
      else
        format.html { render :edit }
        format.json { render json: @excuse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /excuses/1
  # DELETE /excuses/1.json
  def destroy
    @excuse.destroy
    respond_to do |format|
      format.html { redirect_to excuses_url, notice: 'Excuse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_excuse
      @excuse = Excuse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def excuse_params
      params.require(:excuse).permit(:desc)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/excuses_helper.rb
module ExcusesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/excuses/_form.html.erb
<%= form_for(@excuse) do |f| %>
  <% if @excuse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@excuse.errors.count, "error") %> prohibited this excuse from being saved:</h2>

      <ul>
      <% @excuse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/excuses/edit.html.erb
<h1>Editing excuse</h1>

<%= render 'form' %>

<%= link_to 'Show', @excuse %> |
<%= link_to 'Back', excuses_path %>

app/views/excuses/index.html.erb
<h1>Listing excuses</h1>

<table>
  <thead>
    <tr>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @excuses.each do |excuse| %>
      <tr>
        <td><%= excuse.desc %></td>
        <td><%= link_to 'Show', excuse %></td>
        <td><%= link_to 'Edit', edit_excuse_path(excuse) %></td>
        <td><%= link_to 'Destroy', excuse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Excuse', new_excuse_path %>

app/views/excuses/new.html.erb
<h1>New excuse</h1>

<%= render 'form' %>

<%= link_to 'Back', excuses_path %>

app/views/excuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Desc:</strong>
  <%= @excuse.desc %>
</p>

<%= link_to 'Edit', edit_excuse_path(@excuse) %> |
<%= link_to 'Back', excuses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dailyexcuse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome Time</h1>
<p>No reason to have anything here!</p>